sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

after_success:
  - mvn jacoco:report coveralls:report

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "KuEf8Bs1gcsx2gEGM0SLtTYsmZC+yhg/bEfjAZ8F6pLK9V5vXdEqIGl7jJgO5H0utodemjsBiu0gD0FD4PC/1rkWVblYzdePMWQgzRsnzXCd47GAirM/cqFMhhZ4Vzfu8UDHvzapWKhohE9wv8a+TBnLm1OZgbuZ/V3/AAoU/H4zVL8JrNrFqOYriL03ofpuEjfxrM/LJyM71L6evJAnEnkq+w3bKeqqVvIJNSMb6ubsmtbawbcyhbDA+0Bf/N5xgu5Y6+lnjuWip96fThTrc/gypBISdvH8wZ8A1hjz7aYirmdYP634XQmxBgoyXgeRTypU8hTdBVF3djZFyCNykCwl1iHW100mMxhslSOGn8V/uncv5IHfnbNJmIYYQArM20T6e2yQFCp9agbRcFeHKCogmvi+z4yBs5N/eDtWYPM+VnjDRLHJzJSKXVlaKS8Lfw7AtuRnrPbwvFs61oXbbfDYoof1xZKc2SxUeq6wAVWYuwckDGXU41gRNzR/L/j7h82avLXswyPTJBHWga3xC6lgreA8PQz8jt/5SgQ/0S2kDwrQujGy+LFwUR6MnUXwq/h+LP9hbqy2JDlm52qUFmNC7h7Zs/BLBZpPDY/qSxdTYWsnki7AQNIh7s+9RuPgaaWwz7pQbfrt/dPFd8/t2KbZafXMFTtdz+V+LQoLMn4="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "qbOXZZUlQyBh1wGKRYgWiuyraVn/NJa1ZS0gKxzL7Bs7kr8EuG1pMVtHG2qA1OIY2ooIputlqyP4FRV8WoRBb6mxgRfSky2plIfOkP0gZ0ZSG++014Ga0sx76VWaCeeikZizzzb1fiOLnXcrhliIBTKi4xxvKHwhRoSgmvM+0zIDAdVavpkGYf1z++b3Cfd66lr4rby0BWr5XQghljvmL06Dn55UaJHbfmeLULmZ4Yste3vCuHsbRpa+zSfTMtlyMOjrDSD+Zyt8JSA3n4GLBAKvdSBzdnqxQSTF65354evbbAuKcT0O8UnvypjAEkklSXKzxBbeNaK2b2ogkJsepNR0arifrPwQM2ReITLPDmDloDDWL54LrsSqyJPNvGQtOby3XPASkd6a1VISOrvYkdKTIeaGwi5aPh6luSDJMMLFkxIN1ujtVwqjoEQw9InxxBIcojRHW0qpuUR2wFVp+WF3t3bxFSz4z/egZQqFj7Zy47+kg98eyKECIZeGYZ2LATXqE4F4BSBUo82fxyvUy4MYFipo80HippNjAFb/gLzGh1PJIAUbzE/ll6l8A1mlg8rUwrrMWfju1BbyAeVLCLlQUkpN2/yxqMjVgOkRJUyp5r23bG2+A6rk0NraCOPHA9dIy23FYFD7L2aG7R+1r7QJxO1szrZ5jEbgzDpSRLk="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "VGqgJ8FyvToV5vK9fiaVZiV9dwwUKLmubRGk4N8rB6ZXXBrfDmncYFwr1c+saOwneKIrHfauH2vpmotJNPZX5/1Fpfz/jGVerj3oQXKX7Sof6hsdTUX+U8tD4GUYO684eM0TpOwc3VAdaRAfb0ruLBaGd1QB1mQqf+H08RjMeOfSOVTmjsgUqL6z61fzp8LXVWvFKD8hy+wL4kPjOubhV6MbZ0dblzppMrs0runc19/aFgTueJqYysE7/m5ILJUALcokeh1FVQKaKd9Lh9eqGkwZ5UliL0CU0L3+CNhDu2a58EbTl58p20XRDtIHL1r/NfareRAV5DpqqXhNYrP+RGHpSwOpbFrcN0aRelhHGcP8LrwGWFrcd+qGbngZW3OydJz77yrc0EOK0G/Ec67QJcvtusxj9/dL1TBIJaLRO8q964Wp8xfKyfDSHprUd90RhGN3h23l4XxOZvGSOn0IeO6/uiB1gmt8CU5SDk8T3JOckKkDFbwD6K5B+0zQe2+8qJslEx0fHycOYZbNLnR/t3YzLst0wBmwvFZR56B5TFwfmKGMx5aaB9OcvMWFC6nQbwu8LTp/PupsS7b1pADFLVqT6IAZ+2cPBEBxFxNdqcXsRy78+CGK9eNmKfe1Iu9/7u4g2LnXXAcBkoS8xRQGYHd+LOw9kvRLwTTVi+mKOpc="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "DvzjJ+7fDwkS3AVjJbdW4Z731T/JE+2EHqXPy5ZkUbHquSTUUtkQgkZaEm14Lt3x60fSjdBN92qw4hhSj1dnn+6l305OJGotaTbcUsJxRmYK8sbIhZjuonixeym+BCmelAPI12mTKWI3iMGFaCE48C7E0w3j8J3ayD7h5nJmFdGJZDKPBnruwPqi5LvID+rNb5T8oD0zjATwdhLuCl+EPiWvuCswCledHMVM1iSRqd54wUb5DBK5RTIirzdJhE2H/qCa1HwVPtACdYlWWIYYfjyvheqYWpk05+ycD0GBQ69VPg+B1+rtK+rHnBlGzILPGG8vrrNZ0u+9r9GoKtkZ/DZWBu+AbvlFfBKFoneR0MrZR76RloAe6VeV1zOiBg8wHpiGawOt3K1JqdzifdtKG9GOeCXUQAJaz9u6U56s1cUXffwpkev+wgLRSL5aXJMsvOtkK9e28E2iRhv4mFfpjEnZXkpM2PynRJnV8dFZDPRfrO+2l9BrQXos9XzDSSqJGZKblR6O3XqZRS1YV6AuXtnaAUjRCGADfZ8vd2T11fYG6fIz+gHkl+ymmCQDZZq5dwOYZKOo0kD5HAXIEEHZRIn1SVPUSlqiS1EChqu2kGyjMErmb2T5wz77y//F0F/xX09qLvOVJwYERx9H4uUxzRXAKP/8sHj1lud1AIy+5/Y="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "cUClmME+PWOZdt5PAc/TSilOxedkI2OgmxgQmerqTYT++wy/LZUcBDXojhcq5XPhsyva/hbT4Ch07KNsYjYwm/2XxR0lidxYPiuP5htFw2xw6skEJ0YcTzbihNzalHIclcbac9Keri23dwbSjtYH7yMWNjh34jaS+pSQ5i95RjwDQGgGFgUNwTyTHquW4O3LTrjudbx/dGC+lF1Xn2oxtrncfzLPFJU3InQkS+nwd6ppQ0BAu2OmgjK13PqwuI4o69h8qnZVlpfP3vI9rgXzkbEmh7cPu487B0NSyAUimyoqvECWeUdAL5YEBw315/o4I73PaIwmt0/dNaHekxLfHoZCVcr7G+DoDc0Lca+byr15/m0kFfN38L6F/rqWzBv4TAx0EyOS+sHpsOHj0obIzVmWgqZQwCbnVK87Izt4G/6NPBM8z3RHa/x/fUvtpvHE6GrTSat2rkKrlQaR/p5uV+UQ3vUVwy07vnfvMHIxHOv5EY9OuY7jCJGHhCfdj56wSEtyjh7EnhZEwAmZ0NZ0IX4TziAgU3ubjZ7zgYR0CP6SiepE4WmpXHMWVQM5f/5hv5Rzk7t1gDumEM24XkTZe/717fV23XnB50ZH8cT1/2f1L0quA5LMi6RBkuwZGLYfFMim7N07yJ89Ev+SBfk5qgaXqrWxTjnAwD4/mqtWSj8="
